modLoader="javafml"
loaderVersion="[2,)"
license="Academic Free License v3.0"

[[mods]]
modId="minecraft_ultimate_neoforge"
version="0.1.0"
displayName="Minecraft Ultimate"
displayURL="https://mcreator.net"
credits="Created using mod maker MCreator - https://mcreator.net/about"
authors="samuel vrignaud"
description="build 01"

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.minecraft_ultimate_neoforge]]
    modId="neoforge"
    type="required"
    versionRange="[20.6.117,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.minecraft_ultimate_neoforge]]
    modId="minecraft"
    type="required"
    versionRange="[1.20.6]"
    ordering="AFTER"
    side="BOTH"




# Start of user code block dependencies configuration
# End of user code block dependencies configuration